[package]
name = "poker-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
[dependencies.uuid]
version = "1.12.1"
features = [
    "v4",                # For generating random UUIDs
]