name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build poker-client
      run: cargo build --verbose --manifest-path=poker/poker-client/Cargo.toml
    
    - name: Build poker-server
      run: cargo build --verbose --manifest-path=poker/poker-server/Cargo.toml
    
    - name: Run tests for poker-client
      run: cargo test --verbose --manifest-path=poker/poker-client/Cargo.toml
    
    - name: Run tests for poker-server
      run: cargo test --verbose --manifest-path=poker/poker-server/Cargo.toml
